## Graphe interactif (temperatures moyennes HadCRUT5) préparation données en json à destination de d3.js
#### Sources : 
##### Téléchargement des données, licence, citations : https://www.metoffice.gov.uk/hadobs/hadcrut5/ . Fichier intéressant : HadCRUT.5.0.1.0 analysis / HadCRUT5 analysis time series: ensemble means and uncertainties / 1er tableau Summary series : Global (NH+SH)/2, format CSV, Monthly. :
##### Lien de téléchargement des données : https://www.metoffice.gov.uk/hadobs/hadcrut5/data/HadCRUT.5.0.2.0/download.html
##### Fichiers à télécharger :
- HadCRUT.5.0.2.0 analysis > Summary series : Global(NH+SH)/2, CSV Monthly
- HadCRUT.5.0.2.0 analysis > Summary series : Global(NH+SH)/2, CSV Annual
##### Licence d'utilisation des données : https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/.

#### Mode d'emploi de mise à jour : 
- aller sur : https://www.metoffice.gov.uk/hadobs/hadcrut5/
- cliquer sur DOWNLOAD DATA
- on arrive sur une page avec des tableaux.
- aller dans le tableau "HadCRUT5 analysis time series: ensemble means and uncertainties" (normalement le premier tableau de la page) et télécharger les deux fichiers :
     1/ ligne : Global (NH+SH)/2, colonne : CSV monthly
     2/ Global (NH+SH)/2, colonne : CSV annual
- enregistrer ces deux fichiers dans 02-GRAPH_analyse-temperatures/dataset_brut/
- les renommer et recopier ces noms dans les clés du dictionnaire 'sourceFiles' (voir ci-dessous)
- confirmer la version souhaitée : ref-1961-1990 [ref / période 1961-1990] ou ref-pre-indus [ ref / ère préindustrielle 1850-1900]
- mettre à jour les paramètres sourceFiles et dateFin (avec la bonne date yyyy-mm du dernier mois de la série)
- éventuellement, modifier les paramètres titre, soustitre, curveToDisplay, dateDebut, dateFin, zoomTooltipText, legendeSlider
- exécuter l'ensemble de ce notebook (Cellule > Exécuter tout)
- vérifier le résultat en exécutant 02-GRAPH_analyse-temperatures/ref-pre-indus/graph02_ref-pre-indus.html
- si OK, minifier : ouvrir une console et taper la commande "minif 02 ref-pre-indus"
- exécuter pour vérifier le fichier 02-GRAPH_analyse-temperatures/ref-pre-indus/minification/graph02_ref-pre-indus.min.html
- si OK, ce dernier fichier est prêt à être enregitré sur l'admin du site, comme valeur du champ 'Graph' de l'instance d'un modèle 'SVGD3 Graph', et être intégré dans un article (type de contenu : svgdgraph1 (+fullwindow) ou svgdgraph2 (+fullscreen), documenter le champ texte du contenu sous la forme : 'slug:slug-du-graphique')

#### Données générales - valablespour ref-1961-1990 et ref-pre-indus (données mensuelles et annuelles)

##### A documenter (choix des données à tracer) :

In [65]:
import sys
# version du code html/css/js :
# ref-1961-1990 = ref / 1961-1990, ref-pre-indus = ref / 1850-1900
version = "ref-pre-indus"

# nom des fichiers sources csv (deux séries : annual et monthly)
sourceFiles = {
    "annual": "HadCRUT.5.0.2.0.analysis.summary_series.global.annual.csv",
    "monthly":"HadCRUT.5.0.2.0.analysis.summary_series.global.monthly.csv",
}

# Fichier dataset de sortie:
dataset_path = "staticfolder/dataset.js"

# ===========================================================================================================
# Paramètres du graphique, à entrer :
# Titre :
titre = "Evolution de la temperature terrestre moyenne"
if version == "ref-1961-1990":
    soustitre = "écart par rapport à la période 1961-1990 (d'après HadCRUT5)"
elif version == "ref-pre-indus":
    soustitre = "écart par rapport à la période pré-industrielle 1850-1900 (d'après HadCRUT5)"
else :
    print("Version non compatible")
    sys.exit()

# définition des courbes affichables :
# permet de choisir l'ordre d'affichage et de sélectionner les courbes à envoyer à l'appli (commenter les courbes qu'on ne veut pas voir)
curveToDisplay = [
    "monthly",
    "monthlyconf",
    "monthlySimpleAvg",
    # "monthlyCenteredAvg",
    # "monthlyWeightedAvg",
    # "monthlyExponentialAvg",  
    "annual",
    "annualconf",
    "annualSimpleAvg",
    # "annualCenteredAvg",
    # "annualWeightedAvg",
    # "annualExponentialAvg",   
    ]   
dateDebut = "1950-01"
dateFin = "2025-02"

zoomTooltipText = "cliquez sur les flèches  et glissez pour zoomer ou dézoomer, puis cliquez sur le graphe pour valider"
legendeSlider = "Taille de la fenêtre pour la moyenne glissante"

# ===========================================================================================================
# exhaustivité des courbes affichables avec leurs paramétrages d'affichage :
# type = linear : courbe classique basée sur un dataset, 
#        margin : surface entre 2 courbes représentant un intervalle de confiance, basée sur dataset
#        xMovingAverage... : courbe basée sur un calcul de moyenne glissante
# source = origine des données = clé de sourceFiles et/ou de dataSet 

featuresAll = {
    "annual": {                                     # nom de la courbe (curve)
        "type": "linear",                           # type : linear (normale), margin (plage de confiance), xxxMovingAverage (moyenne glissante)
        "source": "annual",                         # source des données dans le dataSet (important pour les xMovingAverage) 
        "color": "rgb(120, 150, 200)",              # couleur de la courbe (ou de la plage pour le type margin)
        "thick": 1.0,                               # épaisseur de la courbe
        "legend":"température annuelle",            # libelé de la légende en bas du graphique
    },
    "monthly": {
        "type": "linear",
        "source": "monthly", 
        "color": "rgb(230, 20, 20)",
        "thick": 1.0,
        "legend":"température mensuelle",
    },
    "annualconf": {
        "type": "margin",
        "source": "annual",                         # pour le type margin : correspond aux données originelles
        "color": "rgb(200, 210, 220)",
        "thick": 8,
        "opacity": 0.8,                             # uniquement pour le type margin : permet de régler l'opacité de la plage
        "dashcolor":"rgb(150, 150, 170)",           # uniquement pour le type margin : couleur des ticks d'intervalle
        "dashthick":"2px",                          # uniquement pour le type margin : épaisseur des ticks d'intervalle
        "legend":"annuel: confiance à 95%", 
    },
    "monthlyconf": {
        "type": "margin",
        "source": "monthly", 
        "color": "rgb(220, 200, 200)",
        "thick": 8,
        "opacity": 0.8,
        "dashcolor":"rgb(160, 140, 140)",
        "dashthick":"2px",
        "legend":"mensuel: confiance à 95%", 
    },
    "annualSimpleAvg": {
        "type": "simpleMovingAverage",
        "source": "annual", 
        "color": "rgb(50, 120, 180)",
        "thick": 2.0,
        "legend": "annuel: lissage"
    },
    "annualCenteredAvg": {
        "type":  "centeredMovingAverage",
        "source": "annual", 
        "color": "rgb(100, 140, 100)",
        "thick": 1.5,
        "legend": "annuel: lissage centré"
    },
    "annualWeightedAvg": {
        "type": "weightedMovingAverage",
        "source": "annual", 
        "color": "rgb(200, 200, 100)",
        "thick": 1.5,
        "legend": "annuel: lissage pondéré"
    },
    "annualExponentialAvg": {
        "type": "exponentialMovingAverage",
        "source": "annual", 
        "color": "rgb(100, 160, 140)",
        "thick": 1.5,
        "legend": "annuel: lissage exponentiel"
    },
    "monthlySimpleAvg": {
        "type": "simpleMovingAverage",
        "source": "monthly", 
        "color": "rgb(130, 0, 0)",
        "thick": 2.0,
        "legend": "mensuel: lissage"
    },
    "monthlyCenteredAvg": {
        "type":  "centeredMovingAverage",
        "source": "monthly", 
        "color": "rgb(100, 200, 100)",
        "thick": 1.5,
        "legend": "mensuel: lissage centré"
    },
    "monthlyWeightedAvg": {
        "type": "weightedMovingAverage",
        "source": "monthly",
        "color": "rgb(200, 200, 100)",
        "thick": 1.5,
        "legend": "mensuel: lissage pondéré"
    },
    "monthlyExponentialAvg": {
        "type": "exponentialMovingAverage",
        "source": "monthly", 
        "color": "rgb(0, 160, 140)",
        "thick": 1.5,
        "legend": "mensuel: lissage exponentiel"
    }
}

### 1/ Traitement des données, et création du dataframe et du dataset jason --> réf. 1961-1990

In [66]:
import pandas as pd


# features des données qui seront affichées :
curveFeatures = { curve: featuresAll[curve] for curve in curveToDisplay }
dataSetPanda = {}
dataSetJson = {}

# liste des courbes à tracer directement selon un dataSet 
curveWithDataSet = [curve for curve in curveToDisplay if curveFeatures[curve]["type"] in ["linear", "margin"]]

for curve in curveWithDataSet :

    dataset = pd.read_csv("data/"+sourceFiles[curveFeatures[curve]["source"]])

    if curveFeatures[curve]["type"] == "linear" :
        dataset.drop(["Lower confidence limit (2.5%)", "Upper confidence limit (97.5%)"], axis=1, inplace=True)
        dataset.rename(columns={
            "Time":"date",
            "Anomaly (deg C)":"gap",
        }, inplace=True)
 
    elif curveFeatures[curve]["type"] =="margin":
        dataset.drop(["Anomaly (deg C)"], axis=1, inplace=True)
        dataset.rename(columns={
            "Time":"date",
             "Lower confidence limit (2.5%)":"min",
            "Upper confidence limit (97.5%)":"max",
        }, inplace=True)                

    # ajout du mois quand il n'est pas présent (2023 devient 2023-12, pour correspondre à l'échelle x)
    # Ainsi :
    #   - la moyenne annuelle yyyy est représentée par un point en yyyy-12
    #   - la moyenne annuelle de la dernière année incomplète est quand même en yyyy-12, mais n'est pas tracée.
    if "annual" in curveFeatures[curve]["source"] :        
        dataset["date"] = dataset["date"].apply(lambda d:str(d)+"-12")      #bullet "annuel" au yyyy-12          

    # chargement du dataframe dans un dictionnaire de dataframes :
    dataSetPanda[curve] = dataset
    # chargement du dataframe dans un dictionnaire json :
    dataSetJson[curve] = eval(dataset.to_json(orient="records"))

dataSetPanda['annualconf']

        date       min       max
0    1850-12 -0.589256 -0.246166
1    1851-12 -0.411868 -0.054832
2    1852-12 -0.409382 -0.049416
3    1853-12 -0.430009 -0.110700
4    1854-12 -0.432712 -0.150330
..       ...       ...       ...
171  2021-12  0.725458  0.798353
172  2022-12  0.765258  0.837353
173  2023-12  1.061651  1.138975
174  2024-12  1.141589  1.220011
175  2025-12  1.048175  1.332391

[176 rows x 3 columns]

### 2/ Traitement des données, et création du panda et du dataset jason --> réf. 1850-1900

##### calcul des moyennes de référence :

In [61]:
def firstmonth(yy, date1):
    # retourne le premier mois de l'année de l'intervalle
    # ex : (2012, 2012-03) retourne 03;  (2014, 2012-03 retourne 01) 
    if yy == int(date1[:4]) and date1[4:]:
         return int(date1[-2:])
    return 1

def lastmonth(yy, date2):
    if yy == int(date2[:4]) and date2[4:]:
         return int(date2[-2:])
    return 12


def temperature_range(curve, date1, date2):
    """retourne la liste des dates comprises entre date1 et date2"""
    if curve=="annual":
#         return [str(yy)+"-01" for yy in range(int(date1[:4]), int(date2[:4])+1)]
        return [str(yy)+"-12" for yy in range(int(date1[:4]), int(date2[:4])+1)]

    elif curve=="monthly":
        return ["{}-{}".format(str(yy), str(mm)) for yy in range(int(date1[:4]), int(date2[:4])+1) for mm in [
            "{}{}".format("0", str(month))[-2:] for month in range(
                firstmonth(yy, date1), 
                lastmonth(yy, date2)+1
            )]           
        ]
    
def temperature_moyenne(curve, date1, date2):
    """calcule la température moyenne de curve entre date1 et date2[inclus]"""
    df = dataSetPanda[curve]
    df_range = df[df['date'].isin(temperature_range(curve, date1, date2))]
    return df_range['gap'].mean()

In [62]:
# Calcul des températures moyennes :
daterange = [
    ['1850', '1900'],
    ['1961', '1990'],
    ['1986', '2005'],
    ['2006', '2015'],
    ['2023', '2023'],
]
print("Anomalies de température par rapport à la période 1961-1990 :")
print(f'{"intervalle" : <20} {"moy. mensuelle":20} {"moy.annuelle":15}')

for dr in daterange:
    print(f'{dr[0]+"-"+dr[1] : <20} {temperature_moyenne("monthly", dr[0], dr[1]):10.3f} {temperature_moyenne("annual", dr[0], dr[1]):20.3f}')
print()

print("Anomalies de température par rapport à l'ère pré-industrielle 1850-1900 :")
print(f'{"intervalle" : <20} {"moy. mensuelle":20} {"moy.annuelle":15}')

for dr in daterange:
    dt_mensuel = temperature_moyenne("monthly", dr[0], dr[1]) - temperature_moyenne("monthly", "1850", "1900") 
    dt_annuel = temperature_moyenne("annual", dr[0], dr[1]) - temperature_moyenne("annual", "1850", "1900") 
    print(f'{dr[0]+"-"+dr[1] : <20} { dt_mensuel:10.3f} {dt_annuel:20.3f}')
print()

Anomalies de température par rapport à la période 1961-1990 :
intervalle           moy. mensuelle       moy.annuelle
1850-1900                -0.356               -0.356
1961-1990                 0.008                0.008
1986-2005                 0.349                0.349
2006-2015                 0.614                0.614
2023-2023                 1.100                1.100

Anomalies de température par rapport à l'ère pré-industrielle 1850-1900 :
intervalle           moy. mensuelle       moy.annuelle
1850-1900                 0.000                0.000
1961-1990                 0.364                0.364
1986-2005                 0.706                0.706
2006-2015                 0.971                0.971
2023-2023                 1.457                1.457

## Pour passer des données HadCRUT5 (réf 1961-1990) aux données IPCC (réf 1850-1900) il faut ajouter +0,36 °C (en fait +0,364°C) 
##### => même si la moyenne 1850-1900 calculée dans le réf HadCRUT5 (réf 1961-1990)  est de -0,356°C parce que dans ce référentiel la moyenne 1961-1990 est de 0,08 °C alors qu'elle devrait être à 0.

IPCC : https://www.ipcc.ch/sr15/chapter/chapter-1/
"In summary, this report adopts a working definition of ‘1.5°C relative to pre-industrial levels’ that corresponds to global average combined land surface air and sea surface temperatures either 1.5°C warmer than the average of the 51-year period 1850–1900, 0.87°C warmer than the 20-year period 1986–2005, or 0.63°C warmer than the decade 2006–2015. These offsets are based on all available published global datasets, combined and updated, which show that 1986–2005 was 0.63°C warmer than 1850–1900 (with a 5–95% range of 0.57°C–0.69°C based on observational uncertainties alone), and 2006–2015 was 0.87°C warmer than 1850–1900 (with a likely range of 0.75°C–0.99°C, also accounting for the possible impact of natural fluctuations). Where possible, estimates of impacts and mitigation pathways are evaluated relative to these more recent periods. Note that the 5–95% intervals often quoted in square brackets in AR5 correspond to very likely ranges, while likely ranges correspond to 17–83%, or the central two-thirds, of the distribution of uncertainty."

##### décalage du dataset pour mettre la référence (0°C) sur la période pré-industrielle 1850-1990 :

In [63]:
dataSetPandaRefPreIndus = dict()
dataSetJsonRefPreIndus = dict()

# décalage mensuel :
month_offset = temperature_moyenne("monthly", "1850", "1900")
annual_offset = temperature_moyenne("annual", "1850", "1900")

for curve in curveWithDataSet :
    dataSetPandaRefPreIndus[curve] = dataSetPanda[curve].copy()


dataSetPandaRefPreIndus["monthly"]["gap"] = dataSetPanda["monthly"]["gap"] - month_offset
dataSetPandaRefPreIndus["monthlyconf"]["min"] = dataSetPanda["monthlyconf"]["min"] - month_offset
dataSetPandaRefPreIndus["monthlyconf"]["max"] = dataSetPanda["monthlyconf"]["max"] - month_offset
dataSetPandaRefPreIndus["annual"]["gap"] = dataSetPanda["annual"]["gap"] - annual_offset
dataSetPandaRefPreIndus["annualconf"]["min"] = dataSetPanda["annualconf"]["min"] - annual_offset
dataSetPandaRefPreIndus["annualconf"]["max"] = dataSetPanda["annualconf"]["max"] - annual_offset


print("Offset mensuel ", month_offset, "Offset annuel: ", annual_offset)
for curve in curveWithDataSet :
    
    dataSetJsonRefPreIndus[curve] = eval(dataSetPandaRefPreIndus[curve].to_json(orient="records"))

    print("Curve / 1961-1990: ", curve)
    display(dataSetPanda[curve])
    print("Curve / 1850-1900: ", curve)
    display(dataSetPandaRefPreIndus[curve])

Offset mensuel  -0.35649474167728756 Offset annuel:  -0.35649474082352944
Curve / 1961-1990:  monthly

         date       gap
0     1850-01 -0.674564
1     1850-02 -0.333416
2     1850-03 -0.591323
3     1850-04 -0.588721
4     1850-05 -0.508817
...       ...       ...
2097  2024-10  1.199982
2098  2024-11  1.225049
2099  2024-12  1.133547
2100  2025-01  1.262780
2101  2025-02  1.117786

[2102 rows x 2 columns]

Curve / 1850-1900:  monthly

         date       gap
0     1850-01 -0.318070
1     1850-02  0.023079
2     1850-03 -0.234828
3     1850-04 -0.232226
4     1850-05 -0.152322
...       ...       ...
2097  2024-10  1.556476
2098  2024-11  1.581544
2099  2024-12  1.490042
2100  2025-01  1.619274
2101  2025-02  1.474281

[2102 rows x 2 columns]

Curve / 1961-1990:  monthlyconf

         date       min       max
0     1850-01 -0.981772 -0.367357
1     1850-02 -0.700901  0.034069
2     1850-03 -0.933919 -0.248726
3     1850-04 -0.898259 -0.279183
4     1850-05 -0.761729 -0.255904
...       ...       ...       ...
2097  2024-10  1.140096  1.259867
2098  2024-11  1.168838  1.281261
2099  2024-12  1.077146  1.189948
2100  2025-01  1.211623  1.313936
2101  2025-02  1.059412  1.176160

[2102 rows x 3 columns]

Curve / 1850-1900:  monthlyconf

         date       min       max
0     1850-01 -0.625277 -0.010862
1     1850-02 -0.344406  0.390564
2     1850-03 -0.577424  0.107769
3     1850-04 -0.541765  0.077312
4     1850-05 -0.405234  0.100590
...       ...       ...       ...
2097  2024-10  1.496591  1.616361
2098  2024-11  1.525333  1.637756
2099  2024-12  1.433641  1.546443
2100  2025-01  1.568118  1.670431
2101  2025-02  1.415907  1.532654

[2102 rows x 3 columns]

Curve / 1961-1990:  annual

        date       gap
0    1850-12 -0.417711
1    1851-12 -0.233350
2    1852-12 -0.229399
3    1853-12 -0.270354
4    1854-12 -0.291521
..       ...       ...
171  2021-12  0.761906
172  2022-12  0.801305
173  2023-12  1.100313
174  2024-12  1.180800
175  2025-12  1.190283

[176 rows x 2 columns]

Curve / 1850-1900:  annual

        date       gap
0    1850-12 -0.061217
1    1851-12  0.123145
2    1852-12  0.127096
3    1853-12  0.086140
4    1854-12  0.064974
..       ...       ...
171  2021-12  1.118400
172  2022-12  1.157800
173  2023-12  1.456807
174  2024-12  1.537295
175  2025-12  1.546777

[176 rows x 2 columns]

Curve / 1961-1990:  annualconf

        date       min       max
0    1850-12 -0.589256 -0.246166
1    1851-12 -0.411868 -0.054832
2    1852-12 -0.409382 -0.049416
3    1853-12 -0.430009 -0.110700
4    1854-12 -0.432712 -0.150330
..       ...       ...       ...
171  2021-12  0.725458  0.798353
172  2022-12  0.765258  0.837353
173  2023-12  1.061651  1.138975
174  2024-12  1.141589  1.220011
175  2025-12  1.048175  1.332391

[176 rows x 3 columns]

Curve / 1850-1900:  annualconf

        date       min       max
0    1850-12 -0.232762  0.110328
1    1851-12 -0.055373  0.301663
2    1852-12 -0.052888  0.307079
3    1853-12 -0.073515  0.245795
4    1854-12 -0.076217  0.206165
..       ...       ...       ...
171  2021-12  1.081952  1.154848
172  2022-12  1.121752  1.193848
173  2023-12  1.418145  1.495470
174  2024-12  1.498084  1.576506
175  2025-12  1.404669  1.688886

[176 rows x 3 columns]

#### Ecriture des données dans le dataset jason 
##### --> réf = périodes de 1961-1990 pour ref-1961-1990 / périodes de 1850-1900 pour ref-pre-indus

In [64]:
# cas de la période de référence 1961-1990
if version == "ref-1961-1990":
    dataSet = dataSetJson
# cas de la période de référence 1850-1900
elif version == "ref-pre-indus":
    dataSet = dataSetJsonRefPreIndus
else :
    print("Version non compatible")
    sys.exit()


with open(dataset_path, 'w') as f:
    f.write("\n".join([
        f'const title = "{titre}"',
        f'const subTitle = "{soustitre}"',
        f'const dataSet = {dataSet}',
        "",
        f'const curveFeatures = {curveFeatures}',
        f'const dateDebut = "{dateDebut}"',
        f'const dateFin = "{dateFin}"',
        f'const zoomTooltipText = "{zoomTooltipText}"', 
        f'const legendeSlider = "{legendeSlider}"',
        "let N = 24",     
    ]))